### PR TITLE
Tests and coverage

### PR DESCRIPTION
**Pull request by neutrinog**
This adds support for tests, coverage, and linting.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/word-alignment-tool/3)

### CODE REVIEW

**Comment by neutrinog** [comment]
@klappy this is ready to go. For some reason codecov is not adding a comment. Can you double check that this repo is registered with codecov? You said you installed it for all repos so I expected it to just work.

**Comment by klappy** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/word-alignment-tool/3)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/word-alignment-tool/3#-:-KuvetSodFy_ch4Et3Px:bnfp4nl)*

**Comment by klappy** [comment]
@neutrinog Not sure what else to do to get it to show up...

**Comment by neutrinog** [comment]
maybe codecov just got stuck at some point. Why don't we just merge this in and I'll inspect it again.

**Pull request merged**
